server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  # file upload setting
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  # aws s3 버킷 연동에 필요한 설정이 들어가는 자리
  cloud:
    aws:
      credentials:
        accessKey: aws ???
        secretKey: aws ???
      region:
        static: ap-northeast-2
      s3:
        bucket: orderservice-prod-img8917

# log level setting
logging:
  level:
    root: info
    com:
      playdata:
        productservice:
          common: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}